--para não  dar erro de atribuição comum inválida: alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE curitiba
DATAFILE '/opt/oracle/oradata/XE/CURITIBA1.DBF' SIZE 50M
MINIMUM EXTENT 500K
DEFAULT STORAGE (INITIAL 500K NEXT 500K MAXEXTENTS unlimited PCTINCREASE 0)
PERMANENT -- pelo que vi o permanent aqui é o default e pode ser omitido
ONLINE;

CREATE USER curitiba IDENTIFIED BY admin;
GRANT DBA TO curitiba;
ALTER USER curitiba
DEFAULT TABLESPACE curitiba
QUOTA UNLIMiTED ON curitiba;





CREATE TABLESPACE palotina
DATAFILE '/opt/oracle/oradata/XE/PALOTINA1.DBF' SIZE 50M
MINIMUM EXTENT 500K
DEFAULT STORAGE (INITIAL 500K NEXT 500K MAXEXTENTS unlimited PCTINCREASE 0)
PERMANENT
ONLINE;


CREATE USER palotina IDENTIFIED BY admin;
GRANT DBA TO palotina;
ALTER USER palotina
DEFAULT TABLESPACE palotina
QUOTA UNLIMiTED ON palotina;





CREATE TABLESPACE litoral
DATAFILE '/opt/oracle/oradata/XE/LITORAL1.DBF' SIZE 50M
MINIMUM EXTENT 500K
DEFAULT STORAGE (INITIAL 500K NEXT 500K MAXEXTENTS unlimited PCTINCREASE 0)
PERMANENT
ONLINE;


CREATE USER litoral IDENTIFIED BY admin;
GRANT DBA TO litoral;
ALTER USER litoral
DEFAULT TABLESPACE litoral
QUOTA UNLIMiTED ON litoral;